### ISSUE TITLE
skipUnstable does nothing

### ISSUE THREAD

**Issue by jsamr** [release-it/conventional-changelog#12] opened 2020-08-20 18:10 UTC
First of all, thanks a lot for this great library! The README.md states (emphasis mine):

> Options are passed verbatim to *conventional-recommended-bump* and conventional-changelog.

However, changelog is still produced for pre-releases (tested with rc and alpha). This is the relevant part of my package.json

```json
  "release-it": {
    "git": {
      "commitMessage": "chore: release ${version}",
      "tagName": "v${version}"
    },
    "npm": {
      "publish": true
    },
    "github": {
      "release": true
    },
    "plugins": {
      "@release-it/conventional-changelog": {
        "preset": "angular",
        "infile": "CHANGELOG.MD",
        "skipUnstable": true
      }
    }
  }
```
The option is [documented here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#skipunstable). Result:
![2020-08-20-150851_652x290_scrot](https://user-images.githubusercontent.com/3646758/90808910-209a3d00-e2f7-11ea-8b06-1913cf1c11d5.png)

Please note that `release-it` is not a global install, but an alias to `npx release-it`

**Comment by webpro** [comment] 2020-10-11 12:36
Hmm I would think the options would end up as first argument for `conventionalChangelogCore(options)`. Maybe you can run a `DEBUG=release-it:* release-it [...]` run, this should give more output and also pass the `debug` option to conventional-changelog.

**Comment by jsamr** [comment] 2020-10-11 12:43
@webpro After a little lookup, I think the issue is upstream: https://github.com/conventional-changelog/conventional-changelog/issues/675

**Comment by webpro** [comment] 2021-06-06 09:18
Closing this issue, as the issue is likely upstream. Feel free to re-open or raise another issue.

**Closed by webpro** 2021-06-06 09:18 UTC
